# Generated by Django 3.1 on 2024-08-03 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название покемона')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='Английское название покемона')),
                ('title_jp', models.TextField(blank=True, null=True, verbose_name='Японское название покемона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение покемона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание покемона')),
                ('evolved_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_evolutions', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционирует')),
                ('evolved_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='В кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время появления')),
                ('disappeared_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время исчезновения')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('health', models.IntegerField(default=1, verbose_name='Здоровье')),
                ('strength', models.IntegerField(default=1, verbose_name='Атака')),
                ('defence', models.IntegerField(default=1, verbose_name='Защита')),
                ('stamina', models.IntegerField(default=1, verbose_name='Выносливость')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Название покемона')),
            ],
        ),
    ]
