# Generated by Django 3.1 on 2024-08-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20240803_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolved_from',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolved_to',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions', to='pokemon_entities.pokemon', verbose_name='Эволюция'),
        ),
    ]
