# Generated by Django 3.1 on 2024-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20240624_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='lan',
            new_name='lon',
        ),
    ]
