# Generated by Django 3.1.14 on 2024-08-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20240803_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_name',
            new_name='name_ru',
        ),
    ]
