# Generated by Django 3.1 on 2024-07-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20240624_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Без описания'),
            preserve_default=False,
        ),
    ]
