# Generated by Django 3.1.14 on 2024-08-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20240805_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_name_jp',
            new_name='name_jp',
        ),
    ]
