# Generated by Django 3.1.14 on 2024-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20240805_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Название покемона'),
        ),
    ]
