# Generated by Django 3.1.14 on 2024-08-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20240805_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='name_ru',
            new_name='pokemon',
        ),
    ]
